### ISSUE TITLE
The component stopped working after I updated Home Assistant to version 2021.6.0.

### ISSUE THREAD

**Issue by ZuhauseSYD** [vigonotion/stadtreinigung_hamburg#3]
Component has always worked floorlessly...and is awesome btw.

now afer upgrate to 2021/6 I get this error:

Invalid config
The following integrations and platforms could not be set up:

stadtreinigung_hamburg

**Comment by ZuhauseSYD** [comment]
Possible related to: https://home-assistant-guide.com/2021/06/02/outdated-custom-components-and-integrations-might-break-in-home-assistant-core-2021-6/

**Comment by vigonotion** [comment]
This is the underlying library HA uses, not the integration itself. Please open the issue here: https://github.com/custom-components/sensor.stadtreinigung_hamburg
