### ISSUE TITLE
Library still up to date?

### ISSUE THREAD

**Issue by AVIENG** [vigonotion/stadtreinigung_hamburg#5]
Hi! I am trying to work with this library but it doesn't seem to work anymore... Is there an issue on my side or has the website maybe changed something so the code isn't valid anymore?

**Comment by vigonotion** [comment]
The website has changed, I'm working on it but it might take a while

**Comment by vigonotion** [comment]
Actually @fabsenet just made a PR that fixed the library, see #4.
So the library should work now!
